# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: video.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'video.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bvideo.proto\x12\x05video\"&\n\x11VideoFrameRequest\x12\x11\n\tcamera_id\x18\x01 \x01(\t\"@\n\nVideoFrame\x12\x11\n\tcamera_id\x18\x01 \x01(\t\x12\x0b\n\x03img\x18\x02 \x01(\x0c\x12\x12\n\ntime_stamp\x18\x03 \x01(\x03\"4\n\x0fGetFrameRequest\x12\x11\n\tcamera_id\x18\x01 \x01(\t\x12\x0e\n\x06latest\x18\x02 \x01(\x08\"\x1c\n\x0eHealthCheckReq\x12\n\n\x02ok\x18\x01 \x01(\x08\"\x1e\n\x10HealthCheckReply\x12\n\n\x02ok\x18\x01 \x01(\x08\x32\xc5\x01\n\rVideoStreamer\x12=\n\x0cStreamFrames\x12\x18.video.VideoFrameRequest\x1a\x11.video.VideoFrame0\x01\x12\x36\n\tGetFrames\x12\x16.video.GetFrameRequest\x1a\x11.video.VideoFrame\x12=\n\x0bHealthCheck\x12\x15.video.HealthCheckReq\x1a\x17.video.HealthCheckReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'video_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VIDEOFRAMEREQUEST']._serialized_start=22
  _globals['_VIDEOFRAMEREQUEST']._serialized_end=60
  _globals['_VIDEOFRAME']._serialized_start=62
  _globals['_VIDEOFRAME']._serialized_end=126
  _globals['_GETFRAMEREQUEST']._serialized_start=128
  _globals['_GETFRAMEREQUEST']._serialized_end=180
  _globals['_HEALTHCHECKREQ']._serialized_start=182
  _globals['_HEALTHCHECKREQ']._serialized_end=210
  _globals['_HEALTHCHECKREPLY']._serialized_start=212
  _globals['_HEALTHCHECKREPLY']._serialized_end=242
  _globals['_VIDEOSTREAMER']._serialized_start=245
  _globals['_VIDEOSTREAMER']._serialized_end=442
# @@protoc_insertion_point(module_scope)
